language: python
python:
 - "3.6"
cache: pip
install:
 - pip install -r requirements.txt
 - pip install coveralls
before_script:
 - export SECRET_KEY="secret"

script:
 - pytest
 - pytest --cov=app

after_success:
 - coveralls
